### ISSUE TITLE
/lib64/libc.so.6 issue

### ISSUE THREAD

**Issue by mianlee** [wdecoster/chopper#12]
Dear Wouter De Coster:

When I install ready-to-use binary chopper, and I used [chopper-musl.zip](https://github.com/wdecoster/chopper/releases/download/v0.5.0/chopper-musl.zip) as you mentioned in previous issues. I still have the same issue, see screenshot.

I am running centos7.
 
![屏幕截图 2023-08-09 232428](https://github.com/wdecoster/chopper/assets/32915883/d3a5578b-3205-448f-a832-e6fb21119342)

**Comment by mianlee** [comment]
Thank you so much !

**Comment by wdecoster** [comment]
Do you have the same problem when installing from bioconda?

**Comment by Freemacl** [comment]
Hi, I am having the same problem. I used both the linux and musl zip file listed above. This is on a cluster where conda use is discouraged.

**Comment by wdecoster** [comment]
Hi, 

Thanks for reporting this. I do not yet know what is happening, but could you try with this binary? 
[chopper-musl.zip](https://github.com/wdecoster/chopper/files/12534843/chopper-musl.zip)

Wouter

**Comment by Freemacl** [comment]
Hi Wouter, that one worked!
