### ISSUE TITLE
Cannot Download Chopper

### ISSUE THREAD

**Issue by paopaoch** [wdecoster/chopper#15]
Hello.

I have been trying to download Chopper on my Macbook Pro M1. I tried installing via Conda as suggested and it keeps telling me it cannot find Chopper. I also tried downloading the released files and that did not work either as my MacBook thinks that it is malware. Could I have more precise installation instructions? I do not write rust myself so I don't know where to find the solutions.

Thank you so much.

**Comment by wdecoster** [comment]
Hmm weird! Can you tell me the exact error message when you try `conda install chopper`? And regarding your MacBooks security settings, unfortunate that you cannot work around that. But it is not malware :)

**Comment by paopaoch** [comment]
Hello. Thank you for your prompt reply. I have attached the image here and my conda version is conda 23.7.2

<img width="1431" alt="image" src="https://github.com/wdecoster/chopper/assets/85437284/715c51a0-0696-449c-9f44-2c2bc10ab667">

Thanks so much again for this!

**Comment by wdecoster** [comment]
I don't know what is wrong. 

Can't you override your mac when downloading the binary? Or download with wget/curl from the terminal?

**Comment by paopaoch** [comment]
I override my mac and I think it works. Would be good to know why conda doesn't work though as it worked with my older laptop.

I'll close this issue now. Thanks again for your help!
