### ISSUE TITLE
Nanopore barcode/adapter detection

### ISSUE THREAD

**Issue by Ge0rges** [wdecoster/chopper#16]
Hello,

I was wondering if there are any plans to add Nanopore adapter and/or barcode detection.

Thanks

**Comment by wdecoster** [comment]
Hi,

Thanks for the suggestion. I understand that could be useful, but I don't think chopper will do a better job than e.g. guppy for adapter trimming.

Wouter

**Comment by Ge0rges** [comment]
That makes sense. I've just been wondering what the best way to QC guppy's effectiveness at finding adapters and barcodes is.
