### ISSUE TITLE
Recommended defaults?

### ISSUE THREAD

**Issue by jolespin** [wdecoster/chopper#20]
In the example you have the following: 

```
gunzip -c reads.fastq.gz | chopper -q 10 -l 500 | gzip > filtered_reads.fastq.gz
```

Is this what you would recommend for the default settings?  I'm adding this to my VEBA software suite (https://github.com/jolespin/veba) so I want to include some decent defaults that could be used in most cases. 

Thanks!

**Comment by wdecoster** [comment]
Hi,

I would say that the defaults are highly dependent on the application, e.g. Assembly vs reference alignment

**Comment by jolespin** [comment]
What about assembly?

**Comment by wdecoster** [comment]
I don't know if I dare to suggest defaults that would work fine in most scenarios, e.g. duplex will have higher accuracy than simplex sequencing, you could filter a little more stringent on length for ultra-long libraries... Do you have an idea which data type to expect?

**Comment by jolespin** [comment]
The most practical use case would be genome assemblies for microeukaryotes like yeast.  The second most common use case would be larger amplicons like full length 16S.  Last use case would be actual community wide full metagenomes.

**Comment by wdecoster** [comment]
I can't propose defaults that would make sense in all those scenarios. This is difficult. I think the most correct would be to leave this to the end user, if possible.
