### ISSUE TITLE
Not running on aarch64

### ISSUE THREAD

**Issue by ImagoXV** [wdecoster/chopper#22]
Hi there, I'm trying to run chopper on an aarch64 architecture from release. 
It works perfectly fine on my amd64. 

Is there any way to make it works on an aarch64 ? 

Thanks for your time 

Arthur Cousson

**Comment by wdecoster** [comment]
Have you tried a musl build?

**Comment by ImagoXV** [comment]
No, I did not, that's my first interaction with aarch64. 

I'll give it a try and keep you updated

**Comment by ImagoXV** [comment]
It's not working neither 

```
$ ./chopper 
-bash: ./chopper: cannot execute binary file: Exec format error
```

```
$ file chopper
chopper: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=0602da3ae9dd9e39879c74880e9f70ac449e4278, with debug_info, not stripped
```

**Comment by wdecoster** [comment]
Okay, I don't have any experience using aarch64, but I will look into this

**Comment by ImagoXV** [comment]
Maybe if you provide the source code, I can compile it for aarch64. But I'm not too familiar with that neither. 

I saw that I might be able to run it with 

```
qemu-x86_64
```

But I did not try yet

**Comment by wdecoster** [comment]
> Maybe if you provide the source code, I can compile it for aarch64. But I'm not too familiar with that neither. 
> 

Well the source code is in the repository. But I will try to cross compile it...

**Comment by ImagoXV** [comment]
Ok I successfully compiled it

https://github.com/jguhlin/minimap2-rs/issues/49#issuecomment-1903784484


Maybe we share the exec ?

**Comment by wdecoster** [comment]
If you have a chopper binary for aarch64 I could add it to the releases :-)

**Comment by wdecoster** [comment]
Has been added to https://github.com/wdecoster/chopper/releases/tag/v0.7.0
Thanks! You may have to do this again for future releases unless I figure out how to do that on my system.

**Comment by ImagoXV** [comment]
Ok, contact me, we'll find a way
