### ISSUE TITLE
Not working on M2 Mac

### ISSUE THREAD

**Issue by stachyris** [wdecoster/chopper#24]
Hi, I am facing a weird issue - log below

``thread` '<unnamed>' panicked at src/main.rs:thread 'thread '120:<unnamed>' panicked at src/main.rs:120:41<unnamed>41:
:
called `Result::unwrap()` on an `Err` value: ReadError(Error { kind: InvalidData, message: "stream did not contain valid UTF-8" })called `Result::unwrap()` on an `Err` value: MissingAt
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

' panicked at src/main.rs:120:41:
called `Result::unwrap()` on an `Err` value: ReadError(Error { kind: InvalidData, message: "stream did not contain valid UTF-8" })
thread '<unnamed>' panicked at src/main.rs:120:41:
called `Result::unwrap()` on an `Err` value: MissingAt ``

This is my code 
`` gunzip -c ./00_Nanopore_Data/SO_12538_WBS_Sample2.fastq.gz | chopper -q 7 2> chopper.log | gzip > ./01_Trimmed_Data/SHAL_ONT_filtered.fq.gz ``

This seems to be coming from some config/incompatibility with the OS? I did download the compiled binary for Mac OS and also Conda install is not working. 

I am on a M2 Mac Sonoma. Would be great if you can help me out what's going on?! 

Thank you
best, 
Vinay

**Comment by wdecoster** [comment]
Do you think you could share your input data? Or do you get the same error for other fastq files as well?

**Comment by wdecoster** [comment]
Well, that is not how you should gzip it. You have made a tar archive, not a gzipped file. A tar archive is to combine multiple files (which you presumably have).  Tar archives are nice to transfer or archvie data, but are not ready to be used by other tools.

You should `gzip yourreads.fastq` to create a gzipped fastq file.

**Comment by stachyris** [comment]
@wdecoster It's working fine with the correct gzipped file. Extremely sorry for the issue. Closing it now. Feel free to delete the issue. 

best, 
Vinay

**Comment by wdecoster** [comment]
Glad to hear that things work! Feel free to let me know if there is anything else I can help with.
