### ISSUE TITLE
Help with --contam parameter 

### ISSUE THREAD

**Issue by NikoLichi** [wdecoster/chopper#25]
Hi there,

I have some scRNA-seq ONT fastq files that were generated following the [FLAMES](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02525-6) protocol. 
When checking for potential contaminants, several Illumina universal adapters exist, and I wonder if chopper could be used to trim those sequences. I saw the `--contam` parameter and wonder if this could be achieved like this(?)

I am aware of other Illumina trimming software like Trimmomatic, but don't know if this would be suitable for long-read data.

Thanks and all the best,
Nicolas

**Comment by wdecoster** [comment]
That is not something that chopper can currently do. I wonder why you would want to remove those though, as an aligner will softclip those without problems.
