### ISSUE TITLE
--contam ：Filter contaminants against a fasta

### ISSUE THREAD

**Issue by zhangguoxuan880** [wdecoster/chopper#39]
The --contam parameter defaults to the amount of similarity that will be filtered out？

**Comment by wdecoster** [comment]
No, it expects a fasta file.

**Comment by zhangguoxuan880** [comment]
Thank you very much for your reply. 
 It be filtered according to this .fa file. Will it be filtered if the sequence is exactly the same, or will it be filtered if it has a certain level of sequence similarity to this .fa file?

**Comment by wdecoster** [comment]
It will be filtered out if the sequence aligns for at least 90% to a sequence in the contaminant fasta file

**Comment by zhangguoxuan880** [comment]
Thank you for your reply. It has been very helpful to me. Good luck!
