### ISSUE TITLE
glibc

### ISSUE THREAD

**Issue by colindaven** [wdecoster/chopper#4]
Hi,

would be nice if you compiled vs an older glibc to make it more compatible. I could load the whole toolchain and compile within my container, or use conda, but sometimes the joy of rust is just running a wget and using the binary.

chopper: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by chopper)
chopper: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by chopper)
chopper: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by chopper)

I get these errors on Ubuntu 20.04 for example.

Thanks,
Colin

**Comment by wdecoster** [comment]
Yes, I agree that would be good. I'll look into it, but yet have to figure out how to do this properly.

**Comment by wdecoster** [comment]
Could you test this executable please?
https://github.com/wdecoster/chopper/releases/download/v0.2.0/chopper-musl.zip

**Comment by colindaven** [comment]
Thanks, seems to work on Ubuntu 1804 and 2004 now!

**Comment by wdecoster** [comment]
Great, feel free to let me know if you encounter further issues.
